[2024-08-12T08:56:38.625+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T08:56:38.645+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_2024-08-12.log_the_data scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-08-12T08:56:38.649+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_2024-08-12.log_the_data scheduled__2024-06-29T00:00:00+00:00 [queued]>
[2024-08-12T08:56:38.649+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-12T08:56:38.710+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): log_the_data> on 2024-06-29 00:00:00+00:00
[2024-08-12T08:56:38.720+0000] {standard_task_runner.py:63} INFO - Started process 5740 to run task
[2024-08-12T08:56:38.724+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_2024-08-12', 'log_the_data', 'scheduled__2024-06-29T00:00:00+00:00', '--job-id', '2911', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmpi42yu6te']
[2024-08-12T08:56:38.728+0000] {standard_task_runner.py:91} INFO - Job 2911: Subtask log_the_data
[2024-08-12T08:56:38.807+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_2024-08-12.log_the_data scheduled__2024-06-29T00:00:00+00:00 [running]> on host 88a939613e48
[2024-08-12T08:56:38.946+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_2024-08-12' AIRFLOW_CTX_TASK_ID='log_the_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-06-29T00:00:00+00:00'
[2024-08-12T08:56:38.947+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T08:56:38.960+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-12T08:56:38.961+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/logging_config.py']
[2024-08-12T08:56:38.971+0000] {subprocess.py:86} INFO - Output:
[2024-08-12T08:56:39.067+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-12T08:56:39.068+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T08:56:39.115+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_2024-08-12, task_id=log_the_data, run_id=scheduled__2024-06-29T00:00:00+00:00, execution_date=20240629T000000, start_date=20240812T085638, end_date=20240812T085639
[2024-08-12T08:56:39.186+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-12T08:56:39.214+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-08-12T08:56:39.253+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
