[2024-08-12T08:57:30.938+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-08-12T08:57:30.956+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_2024-08-12.validate_the_api scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-12T08:57:30.960+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_2024-08-12.validate_the_api scheduled__2024-08-08T00:00:00+00:00 [queued]>
[2024-08-12T08:57:30.961+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2024-08-12T08:57:31.743+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): validate_the_api> on 2024-08-08 00:00:00+00:00
[2024-08-12T08:57:31.747+0000] {standard_task_runner.py:63} INFO - Started process 6912 to run task
[2024-08-12T08:57:31.751+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'etl_2024-08-12', 'validate_the_api', 'scheduled__2024-08-08T00:00:00+00:00', '--job-id', '3122', '--raw', '--subdir', 'DAGS_FOLDER/final_etl.py', '--cfg-path', '/tmp/tmprk5gi4t9']
[2024-08-12T08:57:31.755+0000] {standard_task_runner.py:91} INFO - Job 3122: Subtask validate_the_api
[2024-08-12T08:57:31.892+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_2024-08-12.validate_the_api scheduled__2024-08-08T00:00:00+00:00 [running]> on host 88a939613e48
[2024-08-12T08:57:32.044+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_2024-08-12' AIRFLOW_CTX_TASK_ID='validate_the_api' AIRFLOW_CTX_EXECUTION_DATE='2024-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-08-08T00:00:00+00:00'
[2024-08-12T08:57:32.046+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-08-12T08:57:32.062+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-08-12T08:57:32.063+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /opt/***/data/api_utils.py']
[2024-08-12T08:57:32.076+0000] {subprocess.py:86} INFO - Output:
[2024-08-12T08:57:32.394+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2024-08-12T08:57:32.395+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-08-12T08:57:32.504+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=etl_2024-08-12, task_id=validate_the_api, run_id=scheduled__2024-08-08T00:00:00+00:00, execution_date=20240808T000000, start_date=20240812T085730, end_date=20240812T085732
[2024-08-12T08:57:32.604+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-08-12T08:57:32.618+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
